name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 下载源码
      uses: actions/checkout@v1
    - name: 初始化
      run: |
        sudo -E apt-get -y install gcc-4.8 gcc-4.8-multilib nasm p7zip-full autoconf automake make patch binutils-dev liblzma-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 1
    - name: 编译
      run: |
        make -C umbr
        make -j -C g4dext
        make -j -C g4eext
        make -C grubutils/fbinst
        make -C grubutils/loadbin
        make -C grubutils/makemod
        make -C grubutils/makerom
        make -C grubutils/wee
        make -C grubutils/weesetup
        7z a grubutils.7z grubutils/fbinst/fbinst grubutils/loadbin/*.bin grubutils/makemod/makemod grubutils/makerom/makerom grubutils/weesetup/weesetup

    - name: 上传
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
            g4dext-*.zip
            g4eext-*.zip
            grubutils.7z
