name: release

on:
#  push:
#    branches:
#      - master
#  watch:
#    types: [started]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 下载源码
      uses: actions/checkout@v1
    - name: 初始化
      run: |
        sudo -E apt-get -y install gcc-4.8 gcc-4.8-multilib nasm p7zip-full autoconf automake make patch binutils-dev liblzma-dev gcc-mingw-w64-i686
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 1
    - name: 编译
      run: |
        make -C umbr
        echo make -j -C g4dext
        echo make -j -C g4eext
        echo make -C grubutils/fbinst OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        echo make -C grubutils/loadbin
        echo make -C grubutils/makemod OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        echo make -C grubutils/makerom OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        echo make -C grubutils/wee
        echo make -C grubutils/weesetup OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        echo 7z a grubutils.7z umbr/* grubutils/fbinst/fbinst.exe grubutils/loadbin/*.bin grubutils/makemod/makemod.exe grubutils/makerom/makerom.exe grubutils/makerom/*.bin grubutils/weesetup/weesetup.exe
        pwd
        ls -lh umbr
        7z a umbr.7z umbr/
        ls -lh ./
        cat /home/runner/work/grubutils_umbr/grubutils_umbr/umbr.7z
        
    - name : 生成外链
      uses: actions/upload-artifact@master
      if: always()
      with:
         name: bin
         path: /home/runner/work/grubutils_umbr/grubutils_umbr/umbr/
