name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 下载源码
      uses: actions/checkout@v1
    - name: 初始化
      run: |
        sudo -E apt-get -y install gcc-4.8 gcc-4.8-multilib nasm p7zip-full autoconf automake make patch binutils-dev liblzma-dev
    - name: 编译 umbr
      run: |
        make -C umbr

    - name: 编译 GRUB4DOS 外部命令
      run: |
        make -j -C g4dext
    - name: 编译 GRUB4EFI 外部命令
      run: |
        make -j -C g4eext

#    - name: 编译 fbinst
#      run: |
#        make -C grubutils/fbinst
#    - name: 编译 loadbin
#      run: |
#        make -C grubutils/loadbin
#    - name: 编译 makemod
#      run: |
#        make -C grubutils/makemod
#    - name: 编译 makerom
#      run: |
#        make -C grubutils/makerom
#    - name: 编译 wee
#      run: |
#        make -C grubutils/wee
#    - name: 编译 weesetup
#      run: |
#        make -C grubutils/weesetup
#    - name: 压缩 grubutils
#      run: |
#        7z a grubutils.7z grubutils/fbinst/fbinst grubutils/loadbin/*.bin grubutils/makemod/makemod grubutils/makerom/makerom grubutils/weesetup/weesetup

    - name: 上传
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
            g4dext-*.zip
            g4eext-*.zip
#            grubutils.7z
